apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: recieve-api
  labels:
    app.kubernetes.io/name: recieve-api
    release: prometheus
    finops.ohanyere.io/cost-center: payments
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: recieve-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
