apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: recieve-api
  labels:
    app.kubernetes.io/name: recieve-api
spec:
  hosts:
    - recieve-api.dev.platform.ohanyere.internal
  gateways:
    - istio-system/platform-gateway
  http:
    - route:
        - destination:
            host: recieve-api
            port:
              number: 80
          weight: 100
